# Generated by Django 5.2.8 on 2026-02-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savingsgoal',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
