# Generated by Django 5.2.8 on 2025-11-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='parsed_vendor',
            field=models.CharField(blank=True, default='Unknown Vendor', max_length=128),
        ),
    ]
