# Generated by Django 5.2.8 on 2026-03-03 14:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_alter_receipt_parsed_vendor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date', '-created_at']},
        ),
        migrations.AddField(
            model_name='expense',
            name='anomaly_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='anomaly_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='is_anomaly',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='reviewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('Food', 'Food'), ('Travel', 'Travel'), ('Bills', 'Bills'), ('Entertainment', 'Entertainment'), ('Shopping', 'Shopping'), ('Healthcare', 'Healthcare'), ('Education', 'Education'), ('Groceries', 'Groceries'), ('Fuel', 'Fuel'), ('Investment', 'Investment'), ('Other', 'Other')], default='Other', max_length=20),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['owner', 'date'], name='expenses_ex_owner_i_d056f1_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['owner', 'category', 'date'], name='expenses_ex_owner_i_87a319_idx'),
        ),
        migrations.AddIndex(
            model_name='expense',
            index=models.Index(fields=['is_anomaly', 'reviewed'], name='expenses_ex_is_anom_9873ea_idx'),
        ),
    ]
