# Generated by Django 5.2.8 on 2026-02-07 07:50

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('goals', '0002_savingsgoal_completed_at'),
        ('recurring', '0002_recurringpayment_notes_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reminder_type', models.CharField(choices=[('goal', 'Savings Goal'), ('recurring', 'Recurring Payment'), ('group_expense', 'Group Expense')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('due_date', models.DateField()),
                ('remind_on', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('email_sent', models.BooleanField(default=False)),
                ('in_app_notified', models.BooleanField(default=False)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='goals.savingsgoal')),
                ('recurring_payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recurring.recurringpayment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['remind_on', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_to', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=200)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('failed', 'Failed')], max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('reminder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_logs', to='reminders.reminder')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='ReminderRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('goal', 'Savings Goal'), ('recurring', 'Recurring Payment')], max_length=20)),
                ('days_before', models.IntegerField(help_text='Days before due date (0 = on due date, -1 = after due date)')),
                ('enabled', models.BooleanField(default=True)),
                ('subject_template', models.CharField(max_length=200)),
                ('message_template', models.TextField()),
            ],
            options={
                'unique_together': {('reminder_type', 'days_before')},
            },
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['user', 'remind_on', 'status'], name='reminders_r_user_id_2502f5_idx'),
        ),
        migrations.AddIndex(
            model_name='reminder',
            index=models.Index(fields=['remind_on', 'status'], name='reminders_r_remind__00a879_idx'),
        ),
    ]
