# Generated by Django 5.2.8 on 2026-02-03 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringpayment',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='category',
            field=models.CharField(choices=[('rent', 'Rent'), ('entertainment', 'Entertainment'), ('bills', 'Bills'), ('insurance', 'Insurance'), ('loan', 'Loan'), ('subscription', 'Subscription'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='recurringpayment',
            name='frequency',
            field=models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], default='monthly', max_length=10),
        ),
    ]
